// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtZEfZTq3r330_J0QMUd12m6GyLqYGLNE',
    appId: '1:538919179822:web:c5612f8865f9d0def7b1bf',
    messagingSenderId: '538919179822',
    projectId: 'hocvui-cfa61',
    authDomain: 'hocvui-cfa61.firebaseapp.com',
    storageBucket: 'hocvui-cfa61.firebasestorage.app',
    measurementId: 'G-BG4Q0W3PL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqHxAu0N8_FKaeM9wCLGMLa4SwIsHANSY',
    appId: '1:538919179822:android:b2153721eaabb5dff7b1bf',
    messagingSenderId: '538919179822',
    projectId: 'hocvui-cfa61',
    storageBucket: 'hocvui-cfa61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkUrd9vp3IvNHOd__qW_fdd0hoTpijsiM',
    appId: '1:538919179822:ios:fefc1e259135e00ff7b1bf',
    messagingSenderId: '538919179822',
    projectId: 'hocvui-cfa61',
    storageBucket: 'hocvui-cfa61.firebasestorage.app',
    iosBundleId: 'com.example.thunail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkUrd9vp3IvNHOd__qW_fdd0hoTpijsiM',
    appId: '1:538919179822:ios:fefc1e259135e00ff7b1bf',
    messagingSenderId: '538919179822',
    projectId: 'hocvui-cfa61',
    storageBucket: 'hocvui-cfa61.firebasestorage.app',
    iosBundleId: 'com.example.thunail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtZEfZTq3r330_J0QMUd12m6GyLqYGLNE',
    appId: '1:538919179822:web:7ff04eda828204b8f7b1bf',
    messagingSenderId: '538919179822',
    projectId: 'hocvui-cfa61',
    authDomain: 'hocvui-cfa61.firebaseapp.com',
    storageBucket: 'hocvui-cfa61.firebasestorage.app',
    measurementId: 'G-Q90J325P05',
  );
}
